AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
